KEYMAPOPTS="us us"
HOSTNAMEOPTS="alpinelinux"
DEVDOPTS="mdev"
INTERFACESOPTS="
auto lo
iface lo inet loopback
auto eth0
iface eth0 inet dhcp
"
TIMEZONEOPTS="Europe/Madrid"
PROXYOPTS=none
APKREPOSOPTS="
http://dl-cdn.alpinelinux.org/alpine/latest-stable/main
http://dl-cdn.alpinelinux.org/alpine/latest-stable/community
"
USEROPTS="-a -u -g audio,input,video,netdev thibautvas"
USERSSHKEY="https://raw.githubusercontent.com/thibautvas/vm-init/main/id_rsa.pub"
SSHDOPTS="openssh"
NTPOPTS=none
DISKOPTS="-m sys /dev/vda"
LBUOPTS=none
APKCACHEOPTS=none

mkdir -p -m 750 /etc/doas.d
echo "permit nopass :wheel" > /etc/doas.d/30-wheel-nopass.conf
: > /etc/motd
